### ISSUE TITLE
Open an email that we will be using for business/testing purposes for now

### ISSUE THREAD

**Issue by Nyakaru** [Nyakaru/school-agenda-system#5]
Anyone with an extra phone number can create a new generic email that we will use for testing e.g for nodemailer, africa's talking ......... @koechpetersn @MbugwaSami , please treat this as urgent

**Comment by koechpetersn** [comment]
Email account created for testing purposes >>>> schooltest@gmail.com

**Comment by Nyakaru** [comment]
> Email account created for testing purposes >>>> [schooltest@gmail.com](mailto:schooltest@gmail.com)

Visit the following url (while connected to google with the account above):

https://www.google.com/settings/security/lesssecureapps

There enable less secure apps.
